name: central

services:
  web:
    image: giobyte8/central-web:dev
    container_name: central-web
    ports:
      - 3000:80

  central:
    image: giobyte8/central:dev
    container_name: central
    env_file:
      - central.env

