# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2023-11-11T04:00:55+00:00

from __future__ import annotations

from ipaddress import IPv4Address
from pydantic import BaseModel, Field


class HostStatus(BaseModel):
    uptime: str = Field(
        ..., description='The amount of time the system has been running.'
    )
    ip: IPv4Address = Field(..., description='External IPv4 address for the host.')
